import type { Metadata } from "next";
import "../globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { ModeToggle } from "@/components/mode-toggle";
import { TLocale } from "@/i18n";
import { ToggleLang } from "@/components/toggle-lang";
import { LangProvider } from "@/providers/lang-provider";
import { getDictionary } from "@/get-dictionary";
import { SignIn } from "@/components/sign-in";
import { SignOut } from "@/components/sign-out";
import UserAvatar from "@/components/user-avatar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next ap",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: TLocale }>;
}>) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`,
          "font-sans",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LangProvider dictionary={dictionary}>
            <header className="container flex items-center justify-between py-4">
              <h1>Coffe</h1>
              <div className="flex items-center space-x-3">
                <ToggleLang />
                <ModeToggle />
                <SignIn />
                <SignOut />
                <UserAvatar />
              </div>
            </header>
            <main className="container grow">{children}</main>
            <footer className="container"></footer>
          </LangProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
